export const jobopenings = [
    {
        title: 'Business Development Executive (Only for Female Candidates)',
        company: 'Easeassist',
        location: 'Remote',
        experience: '0+ years Experience',
        description: 'Immediate Joining !! Fast Growing Business Solutions Startup is looking for passionate Female Business Development Professionals who would l...',
        type: 'REMOTE',
        category: 'Full-Time',
        id: 0,
      },
      {
        title: 'Customer Care & Events Executive',
        company: 'Easeassist',
        location: 'Gurugram',
        experience: '1+ years Experience',
        description: 'Looking for a Customer Centric Professional responsible for supporting the design and delivery of the product/Event experience for our custo...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 1,
      },
      {
        title: 'Enterprise Sales Manager',
        company: 'Easeassist',
        location: 'Hyderabad/ Pune/ Bangalore/ Kochi',
        experience: '2+ years Experience',
        description: 'Resourceful and experienced professional whose primary responsibility is to research and pursue new business leads, work on business proposa...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 2,
      },
      {
        title: 'Area Sales Manager',
        company: 'V4U HR SOLUTIONS.COM',
        location: 'Karnataka- Bangalore, Mangalore, Udupi, Hubli, Dharwad, Bellary, Shimoga, Chitradurga, Chikmagalur, Karwar, Haveri, Bidar,Tumkur',
        experience: '0+ years Experience',
        description: 'Top ranked company in edu tech industry',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 3,
      },
      {
        title: 'Lead Generation',
        company: 'Easeassist',
        location: 'Bangalore, Jodhpur, Pune',
        experience: '1+ years Experience',
        description: 'Looking for an ambitious and dynamic professional with 1-6 Years of Experience in Inside Lead Generation/Sales/Business Development for Bang...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 4,
      },
      {
        title: 'Project Manager',
        company: 'Easeassist',
        location: 'Raigarh, Chattisgarh',
        experience: '10+ years Experience',
        description: 'A key professional having responsibility of managing a project successfully during its various stages in its life cycle consisting of initia...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 5,
      },
      {
        title: 'Engineer Mechanical',
        company: 'Easeassist',
        location: 'Raigarh, Chattisgarh',
        experience: '5+ years Experience',
        description: '',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 6,
      },
      {
        title: 'Operations Internship at Refier',
        company: 'Easeassist',
        location: 'Remote',
        experience: '0+ years Experience',
        description: 'Looking for full-time passouts who are looking to build a career in Operations and Customer Experience',
        type: 'REMOTE',
        category: 'INTERNSHIP',
        duration: '2 months',
        id: 7,
      },
      {
        title: 'Business Development Manager (For Gurgaon/ Mumbai/Bangalore Location)',
        company: 'Easeassist',
        location: 'Gurgaon/ Mumbai/ Bangalore',
        experience: '0+ years Experience',
        description: 'Immediate Joining !! Fast Growing HR Tech Startup is looking for passionate Sales Professionals who would like to learn, perform and grow al...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 8,
      },
      {
        title: 'Inside Sales (Only for Females)',
        company: 'Easeassist',
        location: 'Noida',
        experience: '0+ years Experience',
        description: 'Urgent Requirement - Looking for Female Sales Professionals for Inside Selling Job Role at Noida Location',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 9,
      },
      {
        title: 'Engineer Electrical',
        company: 'Easeassist',
        location: 'Raigarh, Chattisgarh',
        experience: '5+ years Experience',
        description: 'Designing, maintaining, implementing, or improving electrical instruments, facilities, components, equipment products, or systems for indust...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 10,
      },
      {
        title: 'Sr. Sales Manager',
        company: 'Learn and Build',
        location: 'Remote',
        experience: '3+ years Experience',
        description: 'Looking for an enthusiastic and ambitious Sales Professional who can manage organizational sales by developing a business plan that covers s...',
        type: 'REMOTE',
        category: 'Full-Time',
        id: 11,
      },
      {
        title: 'IT Project Manager',
        company: 'Easeassist',
        location: 'Remote',
        experience: '1+ years Experience',
        description: 'Immediate Joining !! Fast Growing Business Solutions Startup is looking for passionate IT Project Manager Professionals, who would like to l...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 12,
      },
      {
        title: 'Senior HR Recruiter',
        company: 'Easeassist',
        location: 'Gurugram',
        experience: '1+ years Experience',
        description: 'Looking for someone who can be responsible for all aspects of recruiting for organization and plays a critical role in ensuring it\'s hiring ...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 13,
      },
      {
        title: 'HR',
        company: 'Easeassist',
        location: 'Raigarh, Chattisgarh',
        experience: '5+ years Experience',
        description: 'The Personnel will be responsible for managing the entire HR Functions of Payroll, Compliances, Hiring, Learning, Employee relations, Organi...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 14,
      },
      {
        title: 'Sales /Marketing / Business Development Executive',
        company: 'BRO Services',
        location: 'Pune',
        experience: '0+ years Experience',
        description: 'Job Opportunity in BRO Services( Fast Growing Delivery services, Logistics company) @Balewadi, Pune',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 15,
      },
      {
        title: 'Business Development Leader (For Bangalore/Pune/Jodhpur Location)',
        company: 'Easeassist',
        location: 'Bangalore/ Pune/ Jodhpur',
        experience: '2+ years Experience',
        description: 'Looking for an experienced professional with 2-12 Years of Experience in Inside Sales/Business Development for Bangalore/Jodhpur/Pune Locati...',
        type: 'INOFFICE',
        category: 'Full-Time',
        id: 16,
      },
      {
        title: 'Career Guide - Business Development (Internship + PPO)',
        company: 'Easeassist',
        location: 'Remote',
        experience: '0+ years Experience',
        description: 'Looking for an ambitious fresher and experienced professionals who look forward to work and grow in one of the best edTech organisation',
        type: 'REMOTE',
        category: 'Full-Time',
        id: 17,
      },
      {
        title: 'Sales Intern',
        company: 'BRO Services',
        location: 'Pune',
        experience: '0+ years Experience',
        description: 'Internship Opportunity in BRO Services( Fast Growing Delivery services, Logistics company) @Balewadi, Pune.',
        type: 'INOFFICE',
        category: 'Internship',
        id: 18,
      },
];